version: '3.8'

services:
  db:
    image: postgres:16
    container_name: ofertaya_subasta_db
    environment:
      POSTGRES_DB: ofertaya-subasta
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    #ports:
    #  - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ofertaya_net

  app:
    build: .
    container_name: ofertaya_subasta_app
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      DB_URL: jdbc:postgresql://db:5432/ofertaya-subasta
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    networks:
      - ofertaya_net

volumes:
  postgres_data:

networks:
  ofertaya_net:
